--
-- PostgreSQL database dump
--

\restrict I1605YN4QAU95ss4QhP3zlXoAKigNV4N1K74Mm0obLoGovgfmCeWPYb6hHv79St

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: materia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.materia (
    id bigint NOT NULL,
    cor character varying(7) NOT NULL,
    nome character varying(100) NOT NULL,
    usuario_id bigint
);


ALTER TABLE public.materia OWNER TO postgres;

--
-- Name: materia_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.materia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.materia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: questao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.questao (
    id bigint NOT NULL,
    comentario text,
    resultado character varying(255) NOT NULL,
    texto text NOT NULL,
    materia_id bigint NOT NULL,
    topico_id bigint,
    CONSTRAINT questao_resultado_check CHECK (((resultado)::text = ANY ((ARRAY['ACERTO'::character varying, 'ERRO'::character varying, 'PENDENTE'::character varying])::text[])))
);


ALTER TABLE public.questao OWNER TO postgres;

--
-- Name: questao_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.questao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.questao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: revisao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.revisao (
    id bigint NOT NULL,
    data_agendada date NOT NULL,
    etapa integer NOT NULL,
    feita boolean NOT NULL,
    intervalo_dias integer NOT NULL,
    topico_id bigint NOT NULL,
    usuario_id bigint
);


ALTER TABLE public.revisao OWNER TO postgres;

--
-- Name: revisao_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.revisao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.revisao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sessao_estudo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sessao_estudo (
    id bigint NOT NULL,
    anotacoes text,
    data_sessao date NOT NULL,
    materia_id bigint NOT NULL,
    usuario_id bigint
);


ALTER TABLE public.sessao_estudo OWNER TO postgres;

--
-- Name: sessao_estudo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sessao_estudo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sessao_estudo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sessao_topico; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sessao_topico (
    sessao_id bigint NOT NULL,
    topico_id bigint NOT NULL
);


ALTER TABLE public.sessao_topico OWNER TO postgres;

--
-- Name: topico; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.topico (
    id bigint NOT NULL,
    concluido boolean NOT NULL,
    data_conclusao date,
    nome character varying(150) NOT NULL,
    materia_id bigint NOT NULL
);


ALTER TABLE public.topico OWNER TO postgres;

--
-- Name: topico_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.topico ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.topico_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    nome character varying(255) NOT NULL,
    senha character varying(255) NOT NULL
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: materia; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.materia (id, cor, nome, usuario_id) FROM stdin;
1	#6c7bff	PORTUGUÊS	\N
2	#34d399	Matemática	\N
7	#6c7bff	Portugues	9
8	#34d399	Matemática	9
\.


--
-- Data for Name: questao; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.questao (id, comentario, resultado, texto, materia_id, topico_id) FROM stdin;
\.


--
-- Data for Name: revisao; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.revisao (id, data_agendada, etapa, feita, intervalo_dias, topico_id, usuario_id) FROM stdin;
25	2026-07-23	1	f	3	4	\N
26	2026-07-27	2	f	7	4	\N
27	2026-08-04	3	f	15	4	\N
28	2026-08-19	4	f	30	4	\N
29	2026-07-23	1	f	3	1	\N
30	2026-07-27	2	f	7	1	\N
31	2026-08-04	3	f	15	1	\N
32	2026-08-19	4	f	30	1	\N
33	2026-07-23	1	f	3	5	\N
34	2026-07-27	2	f	7	5	\N
35	2026-08-04	3	f	15	5	\N
36	2026-08-19	4	f	30	5	\N
37	2026-07-24	1	f	3	15	\N
38	2026-07-28	2	f	7	15	\N
39	2026-08-05	3	f	15	15	\N
40	2026-08-20	4	f	30	15	\N
41	2026-07-24	1	f	3	16	\N
42	2026-07-28	2	f	7	16	\N
43	2026-08-05	3	f	15	16	\N
44	2026-08-20	4	f	30	16	\N
49	2026-07-27	1	f	3	20	9
50	2026-07-31	2	f	7	20	9
51	2026-08-08	3	f	15	20	9
52	2026-08-23	4	f	30	20	9
53	2026-07-27	1	f	3	21	9
54	2026-07-31	2	f	7	21	9
55	2026-08-08	3	f	15	21	9
56	2026-08-23	4	f	30	21	9
\.


--
-- Data for Name: sessao_estudo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sessao_estudo (id, anotacoes, data_sessao, materia_id, usuario_id) FROM stdin;
7	Teste \n\n\n\n\n\n\nteste	2026-07-20	2	\N
8	tetst	2026-07-20	1	\N
9	fdfdjdaj\nfdsldjf\nds f	2026-07-20	2	\N
10	teste\n\n\n\n\n\n\n\n\nss	2026-07-21	1	\N
11	SDFASD\n\n\n\n\n\n\n\n\n\nATE	2026-07-21	1	\N
13	dsafddfsf\n\ndsf\nfds\ndastsd	2026-07-24	7	9
14	dsffd	2026-07-24	7	9
\.


--
-- Data for Name: sessao_topico; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sessao_topico (sessao_id, topico_id) FROM stdin;
7	4
8	1
9	5
10	15
11	16
13	20
14	21
\.


--
-- Data for Name: topico; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.topico (id, concluido, data_conclusao, nome, materia_id) FROM stdin;
4	t	2026-07-20	Regra de 3	2
1	t	2026-07-20	ACENTUAÇÃO 2	1
5	t	2026-07-20	Juros	2
15	t	2026-07-21	PONTUAÇÃO	1
17	f	\N	TRIÂNGULO	2
16	t	2026-07-21	INTERPRETACAO	1
20	t	2026-07-24	Teste	7
21	t	2026-07-24	teste 2	7
22	f	\N	teste	8
23	f	\N	teste 1	8
\.


--
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario (id, email, nome, senha) FROM stdin;
1	andrelessa013@gmail.com	André Lessa	$2a$10$LtT0bHtNlNns.SS7xpgD7.qXn2z3fqmTBo30TEVD9c/l6x4NoSAhu
2	andre@gmail.com	andre	$2a$10$gom0Opw8cPXFU5ytpIAOOeCrzQ5ihgErmh9WQg0YTv6bvN5QTxU.2
3	andre1@gmail.com	André	$2a$10$NytD0lhQkKK3iP9TycanOODUHd37Gu052/4GiJ.a5dWqJ3TV3XJd6
4	andre2@gmail.com	André	$2a$10$T7lRKzDWNf.Puf7o0wN0Ce54EtO0Qup4ScNYGC2xQMHwCenapU7Mm
5	andre3@gmail.com	andre	$2a$10$MN0/q9amGtPy9Dj2Qysc5OPHgzspGF.VQGgxHoZd1Cpz4A3s8CLXq
6	andre11@gmail.com	andre	$2a$10$iSVFebQidzJgJesK4mqN/.SSiTyxU7vPQU26hZ6GY8vLRQQduxuzO
7	andre@andre.com	andre	$2a$10$zxGY8gSFBZz5Q7549dnFXeMfovYSD6Kz9vgXGu21Phs1xYZyT0qQS
8	andrelessa013@gmai.com	André Lessa	$2a$10$Gl/CX2BMGUVsFi2tfeDxBO7cYQj9Hnp9new0y359JZiB4FqzhUXAW
9	outrousuario@gmail.com	OUTRO USUARIO	$2a$10$srrnLvAPooRCFFTAEI2RGeFFIZGozoxt.snwKdZUjgAZVj6lQdxvO
\.


--
-- Name: materia_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.materia_id_seq', 8, true);


--
-- Name: questao_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.questao_id_seq', 1, false);


--
-- Name: revisao_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.revisao_id_seq', 56, true);


--
-- Name: sessao_estudo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sessao_estudo_id_seq', 14, true);


--
-- Name: topico_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.topico_id_seq', 23, true);


--
-- Name: usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_id_seq', 9, true);


--
-- Name: materia materia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.materia
    ADD CONSTRAINT materia_pkey PRIMARY KEY (id);


--
-- Name: questao questao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questao
    ADD CONSTRAINT questao_pkey PRIMARY KEY (id);


--
-- Name: revisao revisao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.revisao
    ADD CONSTRAINT revisao_pkey PRIMARY KEY (id);


--
-- Name: sessao_estudo sessao_estudo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessao_estudo
    ADD CONSTRAINT sessao_estudo_pkey PRIMARY KEY (id);


--
-- Name: topico topico_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.topico
    ADD CONSTRAINT topico_pkey PRIMARY KEY (id);


--
-- Name: usuario uk5171l57faosmj8myawaucatdw; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uk5171l57faosmj8myawaucatdw UNIQUE (email);


--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);


--
-- Name: revisao fk1nih9w8oo88qtr5o7umuxp1gv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.revisao
    ADD CONSTRAINT fk1nih9w8oo88qtr5o7umuxp1gv FOREIGN KEY (topico_id) REFERENCES public.topico(id);


--
-- Name: questao fk4mr4u1cqui1iypa7m4jsdvffh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questao
    ADD CONSTRAINT fk4mr4u1cqui1iypa7m4jsdvffh FOREIGN KEY (materia_id) REFERENCES public.materia(id);


--
-- Name: materia fk_materia_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.materia
    ADD CONSTRAINT fk_materia_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);


--
-- Name: revisao fk_revisao_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.revisao
    ADD CONSTRAINT fk_revisao_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);


--
-- Name: sessao_estudo fk_sessao_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessao_estudo
    ADD CONSTRAINT fk_sessao_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);


--
-- Name: topico fk_topico_materia; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.topico
    ADD CONSTRAINT fk_topico_materia FOREIGN KEY (materia_id) REFERENCES public.materia(id) ON DELETE CASCADE;


--
-- Name: sessao_estudo fkbxh594l502e3axqud0em8uipg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessao_estudo
    ADD CONSTRAINT fkbxh594l502e3axqud0em8uipg FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);


--
-- Name: sessao_topico fkf1le5k1xld1q3mk7v7njvqyf4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessao_topico
    ADD CONSTRAINT fkf1le5k1xld1q3mk7v7njvqyf4 FOREIGN KEY (topico_id) REFERENCES public.topico(id);


--
-- Name: sessao_estudo fkh7d1k594jfp4fbac8849vyxnw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessao_estudo
    ADD CONSTRAINT fkh7d1k594jfp4fbac8849vyxnw FOREIGN KEY (materia_id) REFERENCES public.materia(id);


--
-- Name: questao fkqhdxbper7hg611jr99c081n9n; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questao
    ADD CONSTRAINT fkqhdxbper7hg611jr99c081n9n FOREIGN KEY (topico_id) REFERENCES public.topico(id);


--
-- Name: topico fkqq7sbf0ie71p1svk20t930aek; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.topico
    ADD CONSTRAINT fkqq7sbf0ie71p1svk20t930aek FOREIGN KEY (materia_id) REFERENCES public.materia(id);


--
-- Name: sessao_topico fkroi8tk0jdb1bo5bvjsfpu6epx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessao_topico
    ADD CONSTRAINT fkroi8tk0jdb1bo5bvjsfpu6epx FOREIGN KEY (sessao_id) REFERENCES public.sessao_estudo(id);


--
-- PostgreSQL database dump complete
--

\unrestrict I1605YN4QAU95ss4QhP3zlXoAKigNV4N1K74Mm0obLoGovgfmCeWPYb6hHv79St

